### ISSUE TITLE
sorry cannot install!!!

### ISSUE THREAD

**Issue by bubifengyun** [odai-alali/yii2-qrcode-reader#1]
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package odaialali/yii2-qrcode-reader could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by odai-alali** [comment]
Hello bubifengyun

this repo wasn't intended to be published for production, but if you are interested i updated the code and fixed it to be installed
if you are interested in this repo you are welcome to contribute.

i used this library for processing QR https://github.com/dwa012/html5-qrcode

you can install it to try it, follow the Readme

**Comment by bubifengyun** [comment]
Thank you, i have installed successfully by

``` bash
php composer.phar require odaialali/yii2-qrcode-reader "@dev"
```

There's something I need to modify. Great job! thank you very much.
